# Overall Sales

Dashboard link: https://app.powerbi.com/groups/me/reports/6bbe758c-7851-4671-8118-c9f01dc3337e/ReportSectiona95a9ba42ca660167abd?experience=power-bi

### step1 
"DESCRIPTION" 

"Overall sales" generally refer to the total revenue generated by a company, organization, or individual over a specific period. This figure encompasses all income from various products, services, or other revenue-generating activities. Understanding overall sales is crucial for assessing the financial health and growth potential of a business.

Key points to consider when evaluating overall sales include:

Total Revenue: The gross income before any deductions.
Sales Trends: Comparing sales over different periods to identify growth patterns or declines.
Sales Channels: Analyzing sales from different channels such as online, retail, wholesale, etc.
Product Performance: Evaluating which products or services contribute the most to overall sales.
Market Conditions: Understanding external factors that might influence sales, like economic conditions, competition, and consumer behavior.
Sales Forecasting: Projecting future sales based on historical data, market analysis, and other predictive techniques.
Profit Margins: Assessing the profitability of the overall sales by deducting costs from the total revenue.

Snap of Overall sales Dashboard
![Screenshot 2024-06-21 130726](https://github.com/Gurunathan9805/Texti/assets/124778749/3a747bb9-7b58-404e-9527-fa7b7d9ff115)


### Step2
Import the data from excelsheet and tranform the data what we are using in this dashboard

Remove unwanted data and columns in the dataset

### step3
Use some popular charts like barchart, column chart, table view and Donut chart.

### step4
First plot is the bar chart with the column fill of sub-Category , Sum of product sales with region

snap of bar chart

![Screenshot 2024-06-21 131006](https://github.com/Gurunathan9805/Texti/assets/124778749/6eeffcc4-8895-4648-8ab5-f529949f6773)

### Step5
Next visualization is column chart chart with the coordination of Category and sales and profit 

snap of Column chart
![Screenshot 2024-06-21 131151](https://github.com/Gurunathan9805/Texti/assets/124778749/ae69b599-7eef-4be9-a69f-e2a8222d8e7c)


### step6 
Map visualization is too useful to recognise the people where they were mostly use the Category wise products.

snap of Map visualization
![Screenshot 2024-06-21 133504](https://github.com/Gurunathan9805/Texti/assets/124778749/20d3a528-1298-4612-82ec-adacc1b08616)

### step7
Donut chart is helpful to find the highest percentage of sales by state in the USA.

snap of Donut chart
![Screenshot 2024-06-21 131300](https://github.com/Gurunathan9805/Texti/assets/124778749/dab03139-04d1-45ba-95f2-b90702c68f08)

### step8
Finally the Table visualization in the Overall sales report dashboard gives the major details.

snap of Table visualization
![Screenshot 2024-06-21 130845](https://github.com/Gurunathan9805/Texti/assets/124778749/259da139-6caa-488f-9d45-64b32efb2c3c)

These are the details for more useful to understand in what we are doing in this dataset.
